name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: openrndr/setup-opengl@v1.1
    - uses: RpxdYTX/install-glfw-deps@v2
    - name: make
      run: make

